package constants

const TASK_TYPE_TASK = "TASK"
const TASK_TYPE_SUBTASK = "SUBTASK"

const TASK_STATUS_CREATED = "CREATED"
const TASK_STATUS_COMPLETED = "COMPLETED"
const TASK_STATUS_PENDING = "PENDING"
